name: Publish

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [main]
  workflow_dispatch:

env:
  registry: ghcr.io
  image_name: ${{ github.repository_owner }}/n8n-python

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest version
        run: |
          echo "n8n_version=$(curl --silent --header 'Accept: application/vnd.github.v3+json' --url 'https://api.github.com/repos/n8n-io/n8n/releases/latest' | jq --raw-output '.name | sub("n8n@"; "")')" >> $GITHUB_ENV

      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.n8n_version }}
          tags: |
            ${{ env.registry }}/${{ env.image_name }}:latest
            ${{ env.registry }}/${{ env.image_name }}:${{ env.n8n_version }}
